One way arrow on roads
lukasmartinelli/osm-liberty pull request #81
Opened 2020-03-07 22:35 UTC by kylebarron

Preview: https://maputnik.github.io/editor/?style=https://raw.githubusercontent.com/kylebarron/osm-liberty/one-way/style.json

Currently set to a `minzoom` of 15, which seems fine. On merge, the `sprite` key needs to be set back to the default.

[![image](https://user-images.githubusercontent.com/15164633/76153416-ffb39780-6088-11ea-9ef9-a87d8ee1b0ce.png)](https://maputnik.github.io/editor/?style=https://raw.githubusercontent.com/kylebarron/osm-liberty/one-way/style.json#15.29/42.37176/-71.111299)

![image](https://user-images.githubusercontent.com/15164633/76153428-27a2fb00-6089-11ea-9f90-997baa258fcd.png)

2020-03-09 20:13 UTC, orangemug commented
Looks good, one question what would happen to the arrow if the corner in the middle of this image was tighter, would it overflow or would mapbox-gl-js cull it?

<img width="227" alt="Screenshot 2020-03-09 at 20 07 24" src="https://user-images.githubusercontent.com/235915/76253001-ba869580-6241-11ea-9e85-06f2dbbfc8b1.png">

2020-03-09 20:24 UTC, kylebarron commented
I'm not sure. I don't think there's anything keeping the arrow inside the line.

If I take off the road lines, the arrows still display:
![image](https://user-images.githubusercontent.com/15164633/76254171-9dd26980-6211-11ea-8aa5-ee5035721949.png)

But maybe Mapbox automatically prevents displaying the symbols when the line is very curvy. Or maybe I'm missing an option.

2020-03-10 06:11 UTC, pathmapper commented
> I don't know how prevalent -1 is

See https://taginfo.openstreetmap.org/keys/oneway#values

> but to be complete, it would be good to add a backwards arrow to use on those occasions.

We could use the same arrow for this:
Just add a second layer which is filtering for `oneway = -1`. For this layer use the same arrow, but with `"icon-rotate": 180`. @kylebarron would you mind adding this to the PR?

2020-03-10 06:26 UTC, pathmapper requested changes
@kylebarron left some feedback, otherwise it looks good.

2020-03-10 06:26 UTC, pathmapper commented on style.json
> +      "filter": ["all", ["in", "oneway", 1]],
This is simpler:

```suggestion
      "filter": ["==", "oneway", 1],
```

2020-03-10 06:26 UTC, pathmapper commented on style.json
> +        "symbol-spacing": 250,
This is the default value and could be removed:

```suggestion
```

2020-03-10 06:26 UTC, pathmapper commented on style.json
> +        "icon-size": 1
Also the default value and could be removed:

```suggestion
```

2020-03-19 19:30 UTC, kylebarron commented
Ok, I added the one way arrow for `oneway=-1`. If this looks good to go, I'll change the `sprite` url back to the master branch.

2020-03-20 06:33 UTC, pathmapper approved these changes

2020-03-20 06:39 UTC, pathmapper commented
Thanks @kylebarron, looks good to merge.

Yes, please change the sprite url back to the `gh-pages` branch (I think this is what you've meant, there is no `master` branch for historical reasons :smile: ).

2020-03-20 17:22 UTC, kylebarron commented
The `sprite` key is reset now

2020-03-20 19:15 UTC, merged